name: Test Action

on:
  push:
    branches:
      - master

jobs:
  remote:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup remote
        run: |
          echo "${{ secrets.ANTON_KEY }}" | sudo tee /etc/ssh/authorized_keys
          sudo tee /etc/ssh/sshd_config <<EOF
            PasswordAuthentication no
            PubkeyAuthentication yes
            AuthorizedKeysFile /etc/ssh/authorized_keys
            PermitRootLogin no
            Subsystem sftp /usr/lib/openssh/sftp-server
          EOF
          sudo systemctl restart sshd
          echo 'SSH_KNOWN_HOSTS<<EOF' >> $GITHUB_ENV
          echo $(ssh-keyscan localhost) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: With everything
        uses: ./
        with:
          playbook: playbook1.yml
          key: ${{ secrets.ANTON_KEY }}
          known_hosts: ${{ secrets.INVENTORY }}
          directory: test
          vault_password: test
          requirements: requirements.yml
###################
