name: Test
env:
  AWS_REGION_NAME: "us-west-2"

on:
  push:
    branches: [ main ]
jobs:
  part_1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone yuor repo
      uses: actions/checkout@v1
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.ANTON_KEY }}
