name: Ansible

on:
  push:
    branches: [ main ]
    
jobs:
  part_1:
    runs-on: ubuntu-latest
    
    steps:
      - name: write inventory to file
    env:
      INVENTORY: ${{ secrets.INVENTORY }}
      run: 'echo "$INVENTORY" > inventory'
